[req]
distinguished_name = req_distinguished_name
x509_extensions    = v3_ca
prompt             = no

[req_distinguished_name]
CN = HospitalProjectCA

[v3_ca]
basicConstraints        = critical, CA:true
keyUsage                = critical, keyCertSign, cRLSign
nameConstraints         = critical, permitted;DNS:localhost,permitted;DNS:hospitalproject.api.local,permitted;DNS:hospitalproject.local
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always, issuer:always