[req]
default_bits       = 2048
default_md         = sha256
distinguished_name = req_distinguished_name
req_extensions     = v3_req
prompt             = no

[req_distinguished_name]
CN = hospitalproject.local

[v3_req]
subjectAltName       = @alt_names
basicConstraints     = CA:false
keyUsage             = digitalSignature
extendedKeyUsage     = serverAuth
subjectKeyIdentifier = hash

[v3_sign]
subjectAltName         = @alt_names
basicConstraints       = CA:false
keyUsage               = digitalSignature
extendedKeyUsage       = serverAuth
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always, issuer


[alt_names]
DNS.1 = localhost
DNS.2 = hospitalproject.local
IP.1 = 127.0.0.1