worker_processes auto;

pid /tmp/nginx.pid;

events {}

http {
    include /etc/nginx/mime.types;

    server
    {
        listen 443 ssl;
        http2 on;
        server_name localhost hospitalproject.local;

        client_body_temp_path   /tmp/client_temp;
        proxy_temp_path         /tmp/proxy_temp;
        fastcgi_temp_path       /tmp/fastcgi_temp;
        uwsgi_temp_path         /tmp/uwsgi_temp;
        scgi_temp_path          /tmp/scgi_temp;

        ssl_certificate         /etc/nginx/certs/hospitalproject.client.pem;
        ssl_certificate_key     /etc/nginx/certs/hospitalproject.client.key;

        root /usr/share/nginx/html;
        index index.html;

        location /weatherforecast {
            proxy_pass https://hospitalproject.api.local:5229;

            proxy_set_header Host               $host;
            proxy_set_header X-Forwarded-Proto  $scheme;
            proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;

            proxy_ssl_verify              on;
            proxy_ssl_verify_depth        2;
            proxy_ssl_name                hospitalproject.api.local;
            proxy_ssl_server_name         on;
            proxy_ssl_trusted_certificate /etc/nginx/certs/HospitalProject.CA.pem;
        }
    }
}